version: "3.9"
services:
    ui:
        build:
            context: .
            dockerfile: ./packages/ui/Dockerfile
            args:
                PROJECT_DIR: "${PROJECT_DIR}"
        container_name: ui
        environment: 
            NODE_ENV: "${NODE_ENV}"
            PROJECT_DIR: "${PROJECT_DIR}"
            REACT_APP_SITE_NAME: "${SITE_NAME}"
            REACT_APP_SERVER_ROUTE: "${SERVER_ROUTE}"
            REACT_APP_SERVER_PORT: "${SERVER_PORT}"
            REACT_APP_SERVER_LOCATION: "${SERVER_LOCATION}"
            VIRTUAL_HOST: "${VIRTUAL_HOST}"
            VIRTUAL_PATH: "/"
            VIRTUAL_PORT: "${UI_PORT}"
            LETSENCRYPT_HOST: "${VIRTUAL_HOST}"
            LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
        ports:
            - "${UI_PORT}:${UI_PORT}"
        networks:
            - proxy
            - app
        volumes:
            - ./packages/ui:${PROJECT_DIR}/packages/ui:z
            - ./packages/shared:${PROJECT_DIR}/packages/shared:z
        command: /bin/sh -c "chmod +x ./scripts/* && ./scripts/ui.sh"

networks:
  proxy:
    external:
      name: nginx-proxy
  app:

